name: 'Format Java'
on:
  pull_request:
    paths:
    - '**.java'
jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: reformat
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--aosp --replace"
    - name: push changes
      run: |
        [ -z "$(git status --untracked-files=no --porcelain)" ] && exit 0
        git config --local user.name "github-actions[bot]"
        git config --global user.email 'smmckay@users.noreply.github.com'
        git commit -a -m "Update formatting"
        git push
